insert into  IPTREATMENT_PACKAGE ( AILMENT_CATEGORY, COST, TEST_DETAILS,TREATMENT_DURATION,TREATMENT_PACKAGE_NAME  ) Values ( 'Urology', 4000,  'UPT1, UPT2',4, 'Package 1');
insert into  IPTREATMENT_PACKAGE ( AILMENT_CATEGORY, COST, TEST_DETAILS,TREATMENT_DURATION,TREATMENT_PACKAGE_NAME  ) Values ( 'Orthopaedics', 2500,  'OPT1, OPT2',4, 'Package 1');
insert into  IPTREATMENT_PACKAGE ( AILMENT_CATEGORY, COST, TEST_DETAILS,TREATMENT_DURATION,TREATMENT_PACKAGE_NAME  ) Values ( 'Urology', 5000,  'UPT3, UPT4',6, 'Package 2'); 
insert into  IPTREATMENT_PACKAGE ( AILMENT_CATEGORY, COST, TEST_DETAILS,TREATMENT_DURATION,TREATMENT_PACKAGE_NAME  ) Values ( 'Orthopaedics', 3000,  'OPT3, OPT4',6, 'Package 2');
insert into  SPECIALIST_DETAIL (AREA_OF_EXPERTISE, CONTACT_NUMBER, EXPERIENCE, NAME) Values ( 'Orthopaedics', 9898898980,8,'Dr. Vinod Bhave');
insert into  SPECIALIST_DETAIL (AREA_OF_EXPERTISE, CONTACT_NUMBER, EXPERIENCE, NAME) Values ( 'Urology', 9775259493,6,'Dr. Ashoke Shinde');
insert into  SPECIALIST_DETAIL (AREA_OF_EXPERTISE, CONTACT_NUMBER, EXPERIENCE, NAME) Values ( 'Orthopaedics', 8426637582,12,'Dr. V. Kasar');
insert into  SPECIALIST_DETAIL (AREA_OF_EXPERTISE, CONTACT_NUMBER, EXPERIENCE, NAME) Values ( 'Urology', 9889895545,15,'Dr. A.B Devilliers');

